UPDATE trf_ppmc SET Tstamp = CURRENT_TIMESTAMP WHERE Tstamp IS NULL;
UPDATE trf_pers SET Tstamp = CURRENT_TIMESTAMP WHERE Tstamp IS NULL  AND Abr IS NOT NULL;
UPDATE trf_streets SET Avg_pers = (SELECT ROUND(AVG(Value), 0) FROM trf_pers WHERE trf_pers.Abr = 'R197') WHERE trf_streets.Abr = 'R197';
UPDATE trf_streets SET Avg_pers = (SELECT ROUND(AVG(Value), 0) FROM trf_pers WHERE trf_pers.Abr = 'ALT') WHERE trf_streets.Abr = 'ALT';
UPDATE trf_streets SET Avg_pers = (SELECT ROUND(AVG(Value), 0) FROM trf_pers WHERE trf_pers.Abr = 'RSP') WHERE trf_streets.Abr = 'RSP';
UPDATE trf_streets SET Avg_pers = (SELECT ROUND(AVG(Value), 0) FROM trf_pers WHERE trf_pers.Abr = 'JCP') WHERE trf_streets.Abr = 'JCP';
UPDATE trf_streets SET Avg_pers = (SELECT ROUND(AVG(Value), 0) FROM trf_pers WHERE trf_pers.Abr = 'ZU') WHERE trf_streets.Abr = 'ZU';
UPDATE trf_streets SET Avg_pers = (SELECT ROUND(AVG(Value), 0) FROM trf_pers WHERE trf_pers.Abr = 'GC') WHERE trf_streets.Abr = 'GC';
UPDATE trf_streets SET Avg_pers = (SELECT ROUND(AVG(Value), 0) FROM trf_pers WHERE trf_pers.Abr = 'MJ') WHERE trf_streets.Abr = 'MJ';
UPDATE trf_streets SET Avg_pers = (SELECT ROUND(AVG(Value), 0) FROM trf_pers WHERE trf_pers.Abr = 'ZA') WHERE trf_streets.Abr = 'ZA';
UPDATE trf_streets SET Avg_pers = (SELECT ROUND(AVG(Value), 0) FROM trf_pers WHERE trf_pers.Abr = 'COL') WHERE trf_streets.Abr = 'COL';
UPDATE trf_streets SET Avg_pers = (SELECT ROUND(AVG(Value), 0) FROM trf_pers WHERE trf_pers.Abr = 'LAV') WHERE trf_streets.Abr = 'LAV';
UPDATE trf_streets SET Avg_pers = (SELECT ROUND(AVG(Value), 0) FROM trf_pers WHERE trf_pers.Abr = 'ALM') WHERE trf_streets.Abr = 'ALM';
UPDATE trf_streets SET Avg_pers = (SELECT ROUND(AVG(Value), 0) FROM trf_pers WHERE trf_pers.Abr = 'GCA') WHERE trf_streets.Abr = 'GCA';
UPDATE trf_streets SET Avg_pers = (SELECT ROUND(AVG(Value), 0) FROM trf_pers WHERE trf_pers.Abr = 'GO') WHERE trf_streets.Abr = 'GO';
UPDATE trf_streets SET Avg_pers = (SELECT ROUND(AVG(Value), 0) FROM trf_pers WHERE trf_pers.Abr = 'PU') WHERE trf_streets.Abr = 'PU';
UPDATE trf_streets SET Avg_pers = (SELECT ROUND(AVG(Value), 0) FROM trf_pers WHERE trf_pers.Abr = 'FR') WHERE trf_streets.Abr = 'FR';
UPDATE trf_streets SET Avg_pers = (SELECT ROUND(AVG(Value), 0) FROM trf_pers WHERE trf_pers.Abr = 'LG') WHERE trf_streets.Abr = 'LG';
UPDATE trf_streets SET Avg_pers = (SELECT ROUND(AVG(Value), 0) FROM trf_pers WHERE trf_pers.Abr = 'JVG') WHERE trf_streets.Abr = 'JVG';
UPDATE trf_streets SET Avg_ppmc = (SELECT ROUND (AVG(Value),2) FROM trf_ppmc WHERE trf_ppmc.Abr = 'R197' AND trf_ppmc.Zone = 'C') WHERE trf_streets.Abr = 'R197';
UPDATE trf_streets SET Avg_ppmr = (SELECT ROUND (AVG(Value),2) FROM trf_ppmc WHERE trf_ppmc.Abr = 'R197' AND trf_ppmc.Zone = 'R') WHERE trf_streets.Abr = 'R197';
UPDATE trf_streets SET Avg_ppmc = (SELECT ROUND (AVG(Value),2) FROM trf_ppmc WHERE trf_ppmc.Abr = 'ALT' AND trf_ppmc.Zone = 'C') WHERE trf_streets.Abr = 'ALT';
UPDATE trf_streets SET Avg_ppmr = (SELECT ROUND (AVG(Value),2) FROM trf_ppmc WHERE trf_ppmc.Abr = 'ALT' AND trf_ppmc.Zone = 'R') WHERE trf_streets.Abr = 'ALT';
UPDATE trf_streets SET Avg_ppmc = (SELECT ROUND (AVG(Value),2) FROM trf_ppmc WHERE trf_ppmc.Abr = 'RSP' AND trf_ppmc.Zone = 'C') WHERE trf_streets.Abr = 'RSP';
UPDATE trf_streets SET Avg_ppmr = (SELECT ROUND (AVG(Value),2) FROM trf_ppmc WHERE trf_ppmc.Abr = 'RSP' AND trf_ppmc.Zone = 'R') WHERE trf_streets.Abr = 'RSP';
UPDATE trf_streets SET Avg_ppmc = (SELECT ROUND (AVG(Value),2) FROM trf_ppmc WHERE trf_ppmc.Abr = 'JCP' AND trf_ppmc.Zone = 'C') WHERE trf_streets.Abr = 'JCP';
UPDATE trf_streets SET Avg_ppmr = (SELECT ROUND (AVG(Value),2) FROM trf_ppmc WHERE trf_ppmc.Abr = 'JCP' AND trf_ppmc.Zone = 'R') WHERE trf_streets.Abr = 'JCP';
UPDATE trf_streets SET Avg_ppmc = (SELECT ROUND (AVG(Value),2) FROM trf_ppmc WHERE trf_ppmc.Abr = 'ZU' AND trf_ppmc.Zone = 'C') WHERE trf_streets.Abr = 'ZU';
UPDATE trf_streets SET Avg_ppmr = (SELECT ROUND (AVG(Value),2) FROM trf_ppmc WHERE trf_ppmc.Abr = 'ZU' AND trf_ppmc.Zone = 'R') WHERE trf_streets.Abr = 'ZU';
UPDATE trf_streets SET Avg_ppmc = (SELECT ROUND (AVG(Value),2) FROM trf_ppmc WHERE trf_ppmc.Abr = 'GC' AND trf_ppmc.Zone = 'C') WHERE trf_streets.Abr = 'GC';
UPDATE trf_streets SET Avg_ppmr = (SELECT ROUND (AVG(Value),2) FROM trf_ppmc WHERE trf_ppmc.Abr = 'GC' AND trf_ppmc.Zone = 'R') WHERE trf_streets.Abr = 'GC';
UPDATE trf_streets SET Avg_ppmc = (SELECT ROUND (AVG(Value),2) FROM trf_ppmc WHERE trf_ppmc.Abr = 'MJ' AND trf_ppmc.Zone = 'C') WHERE trf_streets.Abr = 'MJ';
UPDATE trf_streets SET Avg_ppmr = (SELECT ROUND (AVG(Value),2) FROM trf_ppmc WHERE trf_ppmc.Abr = 'MJ' AND trf_ppmc.Zone = 'R') WHERE trf_streets.Abr = 'MJ';
UPDATE trf_streets SET Avg_ppmc = (SELECT ROUND (AVG(Value),2) FROM trf_ppmc WHERE trf_ppmc.Abr = 'ZA' AND trf_ppmc.Zone = 'C') WHERE trf_streets.Abr = 'ZA';
UPDATE trf_streets SET Avg_ppmr = (SELECT ROUND (AVG(Value),2) FROM trf_ppmc WHERE trf_ppmc.Abr = 'ZA' AND trf_ppmc.Zone = 'R') WHERE trf_streets.Abr = 'ZA';
UPDATE trf_streets SET Avg_ppmc = (SELECT ROUND (AVG(Value),2) FROM trf_ppmc WHERE trf_ppmc.Abr = 'COL' AND trf_ppmc.Zone = 'C') WHERE trf_streets.Abr = 'COL';
UPDATE trf_streets SET Avg_ppmr = (SELECT ROUND (AVG(Value),2) FROM trf_ppmc WHERE trf_ppmc.Abr = 'COL' AND trf_ppmc.Zone = 'R') WHERE trf_streets.Abr = 'COL';
UPDATE trf_streets SET Avg_ppmc = (SELECT ROUND (AVG(Value),2) FROM trf_ppmc WHERE trf_ppmc.Abr = 'LAV' AND trf_ppmc.Zone = 'C') WHERE trf_streets.Abr = 'LAV';
UPDATE trf_streets SET Avg_ppmr = (SELECT ROUND (AVG(Value),2) FROM trf_ppmc WHERE trf_ppmc.Abr = 'LAV' AND trf_ppmc.Zone = 'R') WHERE trf_streets.Abr = 'LAV';
UPDATE trf_streets SET Avg_ppmc = (SELECT ROUND (AVG(Value),2) FROM trf_ppmc WHERE trf_ppmc.Abr = 'ALM' AND trf_ppmc.Zone = 'C') WHERE trf_streets.Abr = 'ALM';
UPDATE trf_streets SET Avg_ppmr = (SELECT ROUND (AVG(Value),2) FROM trf_ppmc WHERE trf_ppmc.Abr = 'ALM' AND trf_ppmc.Zone = 'R') WHERE trf_streets.Abr = 'ALM';
UPDATE trf_streets SET Avg_ppmc = (SELECT ROUND (AVG(Value),2) FROM trf_ppmc WHERE trf_ppmc.Abr = 'GCA' AND trf_ppmc.Zone = 'C') WHERE trf_streets.Abr = 'GCA';
UPDATE trf_streets SET Avg_ppmr = (SELECT ROUND (AVG(Value),2) FROM trf_ppmc WHERE trf_ppmc.Abr = 'GCA' AND trf_ppmc.Zone = 'R') WHERE trf_streets.Abr = 'GCA';
UPDATE trf_streets SET Avg_ppmc = (SELECT ROUND (AVG(Value),2) FROM trf_ppmc WHERE trf_ppmc.Abr = 'GO' AND trf_ppmc.Zone = 'C') WHERE trf_streets.Abr = 'GO';
UPDATE trf_streets SET Avg_ppmr = (SELECT ROUND (AVG(Value),2) FROM trf_ppmc WHERE trf_ppmc.Abr = 'GO' AND trf_ppmc.Zone = 'R') WHERE trf_streets.Abr = 'GO';
UPDATE trf_streets SET Avg_ppmc = (SELECT ROUND (AVG(Value),2) FROM trf_ppmc WHERE trf_ppmc.Abr = 'PU' AND trf_ppmc.Zone = 'C') WHERE trf_streets.Abr = 'PU';
UPDATE trf_streets SET Avg_ppmr = (SELECT ROUND (AVG(Value),2) FROM trf_ppmc WHERE trf_ppmc.Abr = 'PU' AND trf_ppmc.Zone = 'R') WHERE trf_streets.Abr = 'PU';
UPDATE trf_streets SET Avg_ppmc = (SELECT ROUND (AVG(Value),2) FROM trf_ppmc WHERE trf_ppmc.Abr = 'JVG' AND trf_ppmc.Zone = 'C') WHERE trf_streets.Abr = 'JVG';
UPDATE trf_streets SET Avg_ppmr = (SELECT ROUND (AVG(Value),2) FROM trf_ppmc WHERE trf_ppmc.Abr = 'JVG' AND trf_ppmc.Zone = 'R') WHERE trf_streets.Abr = 'JVG';
UPDATE trf_streets SET Avg_ppmc = (SELECT ROUND (AVG(Value),2) FROM trf_ppmc WHERE trf_ppmc.Abr = 'FR' AND trf_ppmc.Zone = 'C') WHERE trf_streets.Abr = 'FR';
UPDATE trf_streets SET Avg_ppmr = (SELECT ROUND (AVG(Value),2) FROM trf_ppmc WHERE trf_ppmc.Abr = 'FR' AND trf_ppmc.Zone = 'R') WHERE trf_streets.Abr = 'FR';
UPDATE trf_streets SET Avg_ppmc = (SELECT ROUND (AVG(Value),2) FROM trf_ppmc WHERE trf_ppmc.Abr = 'LG' AND trf_ppmc.Zone = 'C') WHERE trf_streets.Abr = 'LG';
UPDATE trf_streets SET Avg_ppmr = (SELECT ROUND (AVG(Value),2) FROM trf_ppmc WHERE trf_ppmc.Abr = 'LG' AND trf_ppmc.Zone = 'R') WHERE trf_streets.Abr = 'LG';
UPDATE trf_streets SET Samples_total = ( SELECT COUNT (*) FROM trf_pers WHERE trf_pers.Abr = 'R197' ) WHERE trf_streets.Abr = 'R197';
UPDATE trf_streets SET Samples_total = ( SELECT COUNT (*) FROM trf_pers WHERE trf_pers.Abr = 'ALT' ) WHERE trf_streets.Abr = 'ALT';
UPDATE trf_streets SET Samples_total = ( SELECT COUNT (*) FROM trf_pers WHERE trf_pers.Abr = 'RSP' ) WHERE trf_streets.Abr = 'RSP';
UPDATE trf_streets SET Samples_total = ( SELECT COUNT (*) FROM trf_pers WHERE trf_pers.Abr = 'JCP' ) WHERE trf_streets.Abr = 'JCP';
UPDATE trf_streets SET Samples_total = ( SELECT COUNT (*) FROM trf_pers WHERE trf_pers.Abr = 'ZU' ) WHERE trf_streets.Abr = 'ZU';
UPDATE trf_streets SET Samples_total = ( SELECT COUNT (*) FROM trf_pers WHERE trf_pers.Abr = 'GC' ) WHERE trf_streets.Abr = 'GC';
UPDATE trf_streets SET Samples_total = ( SELECT COUNT (*) FROM trf_pers WHERE trf_pers.Abr = 'MJ' ) WHERE trf_streets.Abr = 'MJ';
UPDATE trf_streets SET Samples_total = ( SELECT COUNT (*) FROM trf_pers WHERE trf_pers.Abr = 'ZA' ) WHERE trf_streets.Abr = 'ZA';
UPDATE trf_streets SET Samples_total = ( SELECT COUNT (*) FROM trf_pers WHERE trf_pers.Abr = 'COL' ) WHERE trf_streets.Abr = 'COL';
UPDATE trf_streets SET Samples_total = ( SELECT COUNT (*) FROM trf_pers WHERE trf_pers.Abr = 'LAV' ) WHERE trf_streets.Abr = 'LAV';
UPDATE trf_streets SET Samples_total = ( SELECT COUNT (*) FROM trf_pers WHERE trf_pers.Abr = 'ALM' ) WHERE trf_streets.Abr = 'ALM';
UPDATE trf_streets SET Samples_total = ( SELECT COUNT (*) FROM trf_pers WHERE trf_pers.Abr = 'GO' ) WHERE trf_streets.Abr = 'GO';
UPDATE trf_streets SET Samples_total = ( SELECT COUNT (*) FROM trf_pers WHERE trf_pers.Abr = 'PU' ) WHERE trf_streets.Abr = 'PU';
UPDATE trf_streets SET Samples_total = ( SELECT COUNT (*) FROM trf_pers WHERE trf_pers.Abr = 'FR' ) WHERE trf_streets.Abr = 'FR';
UPDATE trf_streets SET Samples_total = ( SELECT COUNT (*) FROM trf_pers WHERE trf_pers.Abr = 'LG' ) WHERE trf_streets.Abr = 'LG';
UPDATE trf_streets SET Samples_total = ( SELECT COUNT (*) FROM trf_pers WHERE trf_pers.Abr = 'GCA' ) WHERE trf_streets.Abr = 'GCA';
UPDATE trf_streets SET Samples_total = ( SELECT COUNT (*) FROM trf_pers WHERE trf_pers.Abr = 'JVG' ) WHERE trf_streets.Abr = 'JVG';
UPDATE trf_streets SET Est_avg_ppmr = (SELECT ROUND(AVG(Avg_ppmr),2) FROM  trf_streets WHERE Avg_ppmr > 0 AND Avg_ppmr IS NOT NULL);
UPDATE trf_streets SET Est_avg_ppmc = (SELECT ROUND(AVG(Avg_ppmc),2) FROM  trf_streets WHERE Avg_ppmc > 0 AND Avg_ppmc IS NOT NULL);
UPDATE trf_streets SET Value_ppers = (SELECT ROUND(AVG(Avg_ppmc / Avg_pers), 2) FROM trf_streets WHERE ((Avg_pers > 0 AND Avg_pers IS NOT NULL) AND (Avg_ppmc > 0 and Avg_ppmc IS NOT NULL)) AND Abr = 'R197' ) WHERE Abr = 'R197';
UPDATE trf_streets SET Value_ppers = (SELECT ROUND(AVG(Avg_ppmc / Avg_pers), 2) FROM trf_streets WHERE ((Avg_pers > 0 AND Avg_pers IS NOT NULL) AND (Avg_ppmc > 0 and Avg_ppmc IS NOT NULL)) AND Abr = 'ALT' ) WHERE Abr = 'ALT';
UPDATE trf_streets SET Value_ppers = (SELECT ROUND(AVG(Avg_ppmc / Avg_pers), 2) FROM trf_streets WHERE ((Avg_pers > 0 AND Avg_pers IS NOT NULL) AND (Avg_ppmc > 0 and Avg_ppmc IS NOT NULL)) AND Abr = 'RSP' ) WHERE Abr = 'RSP';
UPDATE trf_streets SET Value_ppers = (SELECT ROUND(AVG(Avg_ppmc / Avg_pers), 2) FROM trf_streets WHERE ((Avg_pers > 0 AND Avg_pers IS NOT NULL) AND (Avg_ppmc > 0 and Avg_ppmc IS NOT NULL)) AND Abr = 'JCP' ) WHERE Abr = 'JCP';
UPDATE trf_streets SET Value_ppers = (SELECT ROUND(AVG(Avg_ppmc / Avg_pers), 2) FROM trf_streets WHERE ((Avg_pers > 0 AND Avg_pers IS NOT NULL) AND (Avg_ppmc > 0 and Avg_ppmc IS NOT NULL)) AND Abr = 'ZU' ) WHERE Abr = 'ZU';
UPDATE trf_streets SET Value_ppers = (SELECT ROUND(AVG(Avg_ppmc / Avg_pers), 2) FROM trf_streets WHERE ((Avg_pers > 0 AND Avg_pers IS NOT NULL) AND (Avg_ppmc > 0 and Avg_ppmc IS NOT NULL)) AND Abr = 'GC' ) WHERE Abr = 'GC';
UPDATE trf_streets SET Value_ppers = (SELECT ROUND(AVG(Avg_ppmc / Avg_pers), 2) FROM trf_streets WHERE ((Avg_pers > 0 AND Avg_pers IS NOT NULL) AND (Avg_ppmc > 0 and Avg_ppmc IS NOT NULL)) AND Abr = 'MJ' ) WHERE Abr = 'MJ';
UPDATE trf_streets SET Value_ppers = (SELECT ROUND(AVG(Avg_ppmc / Avg_pers), 2) FROM trf_streets WHERE ((Avg_pers > 0 AND Avg_pers IS NOT NULL) AND (Avg_ppmc > 0 and Avg_ppmc IS NOT NULL)) AND Abr = 'ZA' ) WHERE Abr = 'ZA';
UPDATE trf_streets SET Value_ppers = (SELECT ROUND(AVG(Avg_ppmc / Avg_pers), 2) FROM trf_streets WHERE ((Avg_pers > 0 AND Avg_pers IS NOT NULL) AND (Avg_ppmc > 0 and Avg_ppmc IS NOT NULL)) AND Abr = 'COL' ) WHERE Abr = 'COL';
UPDATE trf_streets SET Value_ppers = (SELECT ROUND(AVG(Avg_ppmc / Avg_pers), 2) FROM trf_streets WHERE ((Avg_pers > 0 AND Avg_pers IS NOT NULL) AND (Avg_ppmc > 0 and Avg_ppmc IS NOT NULL)) AND Abr = 'LAV' ) WHERE Abr = 'LAV';
UPDATE trf_streets SET Value_ppers = (SELECT ROUND(AVG(Avg_ppmc / Avg_pers), 2) FROM trf_streets WHERE ((Avg_pers > 0 AND Avg_pers IS NOT NULL) AND (Avg_ppmc > 0 and Avg_ppmc IS NOT NULL)) AND Abr = 'ALM' ) WHERE Abr = 'ALM';
UPDATE trf_streets SET Value_ppers = (SELECT ROUND(AVG(Avg_ppmc / Avg_pers), 2) FROM trf_streets WHERE ((Avg_pers > 0 AND Avg_pers IS NOT NULL) AND (Avg_ppmc > 0 and Avg_ppmc IS NOT NULL)) AND Abr = 'GO' ) WHERE Abr = 'PU';
UPDATE trf_streets SET Value_ppers = (SELECT ROUND(AVG(Avg_ppmc / Avg_pers), 2) FROM trf_streets WHERE ((Avg_pers > 0 AND Avg_pers IS NOT NULL) AND (Avg_ppmc > 0 and Avg_ppmc IS NOT NULL)) AND Abr = 'FR' ) WHERE Abr = 'LG';
UPDATE trf_streets SET Value_ppers = (SELECT ROUND(AVG(Avg_ppmc / Avg_pers), 2) FROM trf_streets WHERE ((Avg_pers > 0 AND Avg_pers IS NOT NULL) AND (Avg_ppmc > 0 and Avg_ppmc IS NOT NULL)) AND Abr = 'GCA' ) WHERE Abr = 'GCA';
UPDATE trf_streets SET Value_ppers = (SELECT ROUND(AVG(Avg_ppmc / Avg_pers), 2) FROM trf_streets WHERE ((Avg_pers > 0 AND Avg_pers IS NOT NULL) AND (Avg_ppmc > 0 and Avg_ppmc IS NOT NULL)) AND Abr = 'JVG' ) WHERE Abr = 'JVG';
UPDATE trf_streets SET Value_ppers = (SELECT ROUND(AVG(Value_ppers), 2) FROM  trf_streets WHERE Value_ppers > 0 AND Value_ppers IS NOT NULL) WHERE Value_ppers = 0 OR Value_ppers IS NULL;
UPDATE trf_streets SET Est_final_ppmc = (SELECT ROUND((Value_ppers * Avg_pers), 2) FROM trf_streets WHERE Avg_ppmc IS NOT NULL AND Avg_ppmc > 0 AND Samples_total > 31);
UPDATE trf_streets SET Est_final_ppmc = (SELECT ROUND((( SELECT AVG(Value_ppers) FROM trf_streets WHERE Value_ppers IS NOT NULL AND Value_ppers > 0) * Avg_pers), 2) FROM trf_streets WHERE Avg_ppmc IS NOT NULL AND Avg_ppmc > 0 AND Samples_total > 31);
UPDATE trf_streets SET Est_final_ppmc = ROUND((Value_ppers * Avg_pers), 2);
UPDATE trf_blocks SET Avg_pers = ( SELECT ROUND(AVG(Value),0) FROM trf_pers WHERE Abr = trf_blocks.Abr AND Alt = trf_blocks.Alt );
UPDATE trf_blocks SET Avg_samples = ( SELECT COUNT (*) FROM trf_pers WHERE Abr = trf_blocks.Abr AND Alt = trf_blocks.Alt );
UPDATE trf_blocks SET Stat_relevant = 'NONE' WHERE Avg_samples < 36;
UPDATE trf_blocks SET Stat_relevant = 'LOW' WHERE Avg_samples >= 36;
UPDATE trf_blocks SET Stat_relevant = 'MEDIUM' WHERE Avg_samples >= 72;
UPDATE trf_blocks SET Stat_relevant = 'HIGH' WHERE Avg_samples >= 108;
UPDATE trf_blocks SET Est_final_ppmc = ( ( SELECT MAX( Est_avg_ppmc ) FROM trf_streets) / ( SELECT AVG(Avg_pers) FROM trf_streets WHERE Samples_total > 0) );
UPDATE trf_blocks SET Est_final_ppmc = (ROUND( ( Est_final_ppmc * Avg_pers ), 2 ));
UPDATE trf_blocks SET m1s = 0.00;
UPDATE trf_blocks SET p1s = 0.00;
UPDATE trf_blocks SET m2s = 0.00;
UPDATE trf_blocks SET p2s = 0.00;
UPDATE trf_blocks SET m3s = 0.00;
UPDATE trf_blocks SET p3s = 0.00;
UPDATE trf_blocks SET m1s = ( SELECT ROUND ( ( Est_final_ppmc - ( ( stdev( SELECT Est_final_ppmc FROM trf_blocks ) ) * 1 ) ), 2 ) FROM trf_blocks );
UPDATE trf_blocks SET p1s = ( SELECT ROUND ( ( Est_final_ppmc + ( ( stdev( SELECT Est_final_ppmc FROM trf_blocks ) ) * 1 ) ), 2 ) FROM trf_blocks );
UPDATE trf_blocks SET m2s = ( SELECT ROUND ( ( Est_final_ppmc - ( ( stdev( SELECT Est_final_ppmc FROM trf_blocks ) ) * 2 ) ), 2 ) FROM trf_blocks );
UPDATE trf_blocks SET p2s = ( SELECT ROUND ( ( Est_final_ppmc + ( ( stdev( SELECT Est_final_ppmc FROM trf_blocks ) ) * 2 ) ), 2 ) FROM trf_blocks );
UPDATE trf_blocks SET m3s = ( SELECT ROUND ( ( Est_final_ppmc - ( ( stdev( SELECT Est_final_ppmc FROM trf_blocks ) ) * 3 ) ), 2 ) FROM trf_blocks );
UPDATE trf_blocks SET p3s = ( SELECT ROUND ( ( Est_final_ppmc + ( ( stdev( SELECT Est_final_ppmc FROM trf_blocks ) ) * 3 ) ), 2 ) FROM trf_blocks );
SELECT * FROM trf_streets WHERE Samples_total > 0 ORDER BY Avg_pers DESC;
SELECT * FROM trf_blocks ORDER BY Est_final_ppmc DESC;
